const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Endboss(),
    ],
    [
        new Cloud(),
        new CloudSecond(),
    ],
    [
        new AirBG_0(),
        new ThirdLayerBG_0(),
        new SecondLayerBG_0(),
        new FirstLayerBG_0(),
        new AirBG(),
        new ThirdLayerBG(),
        new SecondLayerBG(),
        new FirstLayerBG(),
        new AirBG_2(),
        new ThirdLayerBG_2(),
        new SecondLayerBG_2(),
        new FirstLayerBG_2(),
    ],

    [
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
        new Coins(),
    ],

    [
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
        new Bottles(),
    ]

)